# Generated by Django 6.0.2 on 2026-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('results', models.TextField(help_text='Example: 3x ROAS, 200 Leads Generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
